spring:
  data:
    mongodb:
      uri: mongodb://username:password@localhost:27017/studymate

studymate:
  http:
    client:
      config:
        connectionTimeout: 1000
        port: 5057
        readTimeout: 1000
        uri: http://localhost
auth:
  jwt:
    expirationDays: 30
    secret: ${JWT_SECRET}
    issuer: job-offers-backend