spring:
  data:
    mongodb:
      uri: mongodb://root:example@localhost:27017/studymate
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  mail:
    host: smtp.gmail.com
    port: 587
    username: my.gmail@gmail.com
    password: secret
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
studymate:
  http:
    client:
      config:
        connectionTimeout: 1000
        port: 5057
        readTimeout: 1000
        uri: http://localhost
auth:
  jwt:
    expirationDays: 30
    secret: ${JWT_SECRET}
    issuer: study-mate-backend
scheduling:
  enabled: true
reminder:
  scheduler:
    send:
      delay:
        PT30M